DELETE FROM [linnworks].[lw].[Orders]
WHERE source <> 'Maginus';
INSERT INTO [linnworks].[lw].Orders (
    pkOrderId,  
    cFullName,
    cEmailAddress,
    cPostcode,
    dReceivedDate,
    dDispatchBy,
    dProcessedOn,
    fPostageCost,
    fTotalCharge,
    cCurrency,
    nOrderId,
    bReplace,
    Source,
    bProcessed,
    fTax,
    fkCountryId,
    fkPostalServiceId,
    fkPackagingGroupId,
    ReferenceNum,
    ExternalReference,
    PostalTrackingNumber,
    CreateOnly,
    CreatedDate,
    Address1,
    Address2,
    Address3,
    Town,
    Region,
    LifeStatus,
    BuyersPhoneNumber,
    Company,
    SubSource,
    AddressVerified,
    Subtotal,
    PostageCostExTax,
    CountryTaxRate,
    RecalculateTaxRequired,
    ChannelBuyerName,
    HoldOrCancel,
    Weight,
    TotalDiscount,
    fkBankId,
    FulfillmentLocationId,
    SecondaryReferenceNum,
    PostalServiceCost,
    FulfillmentCenterAcknowledge,
    PostageDiscount,
    ConversionRate
)
SELECT
    TRY_CAST(data.pkOrderID AS uniqueidentifier),
    data.cFullName,
    data.cEmailAddress,
    REPLACE(data.cPostCode, CHAR(9), '') AS cPostcode,
    TRY_CAST(data.dReceivedDate AS DATETIME),
    TRY_CAST(JSON_VALUE(CAST(data2.GeneralInfo AS NVARCHAR(MAX)), '$.DespatchByDate') AS DATETIME),
    TRY_CAST(data3.dProcessedOn AS DATETIME),
    data.fPostageCost,
    data.fTotalCharge,
    data.cCurrency,
    data.nOrderId,
    NULL,
    data.Source,
    NULL,
    data.fTax,
    NULL,
    NULL,
    NULL,
    data.ReferenceNum,
    data.ExternalReference,
    data.PostalTrackingNumber,
    NULL,
    NULL,
    data.Address1,
    data.Address2,
    data.Address3,
    data.Town,
    data.Region,
    NULL,
    NULL,
    data.Company,
    data.SubSource,
    NULL,
    data.Subtotal,
    data.PostageCostExTax,
    data.CountryTaxRate,
    NULL,
    data.ChannelBuyerName,
    data.HoldOrCancel,
    NULL,
    data.TotalDiscount,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
FROM 
    [linnworks].[staging].[_airbyte_raw_processed_orders] AS data
    LEFT JOIN [linnworks].[staging].[_airbyte_raw_processed_order_details] AS data2 ON data.pkOrderID = data2.OrderId
    LEFT JOIN [linnworks].[staging].[processed_orders] AS data3 ON data.pkOrderID = data3.pkOrderID
WHERE
    data.SubSource NOT IN ('Staging', 'testorder', 'RMA', 'StagingCF');