INSERT INTO lw.StockItem (
    pkStockItemID,
    ItemTitle,
    ItemNumber,
    ItemDescription,
    CreationDate,
    bLogicalDelete,
    RetailPrice,
    CategoryId,
    Weight,
    PackageGroup,
    BinRack,
    rowguid,
    PurchasePrice,
    BarcodeNumber,
    DimHeight,
    DimWidth,
    DimDepth,
    ShippedSeparately,
    TaxRate,
    fkPostalService,
    bContainsComposites,
    ModifiedDate,
    ModifiedUserName,
    ModifyAction,
    IsArchived,
    IsVariationGroup,
    InventoryTrackingType,
    SerialNumberScanRequired,
    BatchNumberScanRequired,
    Source
)
SELECT 
    TRY_CAST(s.StockItemId AS uniqueidentifier) AS pkStockItemID,
    s.ItemTitle,
    s.ItemNumber,
    s.ItemChannelDescriptions AS ItemDescription,
    TRY_CAST(s.CreationDate AS DATETIME) AS CreationDate,
    NULL AS bLogicalDelete,
    TRY_CAST(s.RetailPrice AS DECIMAL(18,2)) AS RetailPrice,
    TRY_CAST(s.CategoryId AS uniqueidentifier) AS CategoryId,
    TRY_CAST(s.Weight AS DECIMAL(18,2)) AS Weight,
    s.PackageGroupId AS PackageGroup,
    NULL AS BinRack,
    NULL AS rowguid,
    TRY_CAST(s.PurchasePrice AS DECIMAL(18,2)) AS PurchasePrice,
    s.BarcodeNumber,
    TRY_CAST(s.Height AS DECIMAL(18,2)) AS DimHeight,
    TRY_CAST(s.Width AS DECIMAL(18,2)) AS DimWidth,
    TRY_CAST(s.Depth AS DECIMAL(18,2)) AS DimDepth,
    NULL AS ShippedSeparately,
    TRY_CAST(s.TaxRate AS DECIMAL(18,2)) AS TaxRate,
    s.PostalServiceId AS fkPostalService,
    NULL AS bContainsComposites,
    NULL AS ModifiedDate,
    NULL AS ModifiedUserName,
    NULL AS ModifyAction,
    NULL AS IsArchived,
    NULL AS IsVariationGroup,
    TRY_CAST(s.InventoryTrackingType AS INT) AS InventoryTrackingType,
    TRY_CAST(s.SerialNumberScanRequired AS BIT) AS SerialNumberScanRequired,
    TRY_CAST(s.BatchNumberScanRequired AS BIT) AS BatchNumberScanRequired,
    'linnworks' AS Source
FROM 
    [linnworks].[staging].[_airbyte_raw_stock_items] s;
